name: photo_share_capp
description: photo sharing application on cloud platform

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.3

environment:
  sdk: ^2.19.0
  flutter: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  intl: ^0.17.0


  universal_platform: ^1.0.0+1
  universal_html: ^2.0.8
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  flutter_screenutil: ^5.6.1
  uuid: ^3.0.7
  yaml: ^3.1.1
  quiver: ^3.2.1
  url_launcher: ^6.1.9
  rxdart: ^0.27.7
  email_validator: ^2.1.17

  logger: ^1.1.0
  go_router: ^5.1.2
  flutter_dotenv: ^5.0.2
  keyboard_actions: ^4.1.0
  sn_progress_dialog: ^1.1.3
  flutter_native_splash: ^2.2.19
  pwa_update_listener: ^0.1.0

  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  dynamic_color: ^1.6.2
  tinycolor2: ^3.0.1

  gap: ^3.0.1
  loading_animation_widget: ^1.2.0+4
  dropdown_button2: ^2.0.0

  # riverpod
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # map
  geolocator: ^9.0.2
  maps_toolkit: ^2.0.1
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  flutter_map_location_marker: ^5.2.1
  positioned_tap_detector_2: ^1.0.4
  location: ^4.4.0
  flutter_map_marker_cluster: any


  # firebase
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  firebase_storage: ^11.0.14
  flutter_cache_manager: ^3.3.0

  google_sign_in: ^5.4.4

  # local database
  idb_shim: ^2.3.0+1

  ## log download
  file_selector: ^0.9.2+4

  # camera
  image_picker: ^0.8.6+3
  image_picker_for_web: ^2.1.11
  camera: ^0.10.3+2
  path_provider: ^2.0.13
  photo_view: ^0.14.0
  exif: ^3.1.2
  image_size_getter: ^2.1.2
  image: ^4.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  source_gen: ^1.2.6

  flutter_launcher_icons: any

  freezed: ^2.3.2
  json_serializable: ^6.6.1

  import_sorter: ^4.6.0
  flutter_lints: ^2.0.0
  pedantic_mono: any

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/font/NotoSansJP/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/font/NotoSansJP/NotoSansJP-Regular.otf
          weight: 400
    - family: PathwayGothicOne
      fonts:
        - asset: assets/font/PathwayGothicOne/PathwayGothicOne-Regular.ttf
          weight: 400

  assets:
    # - assets/.env
    - assets/image/no_image.jpg
    - assets/image/logo_transparent.png
    - assets/image/logo_transparent_android12.png
